// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: ttrpc/ttrpc.proto
package ttrpc

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type HelloService interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterHelloService(srv *ttrpc.Server, svc HelloService) {
	srv.RegisterService("ttrpc.Hello", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"SayHello": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req HelloRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.SayHello(ctx, &req)
			},
		},
	})
}

type helloClient struct {
	client *ttrpc.Client
}

func NewHelloClient(client *ttrpc.Client) HelloService {
	return &helloClient{
		client: client,
	}
}

func (c *helloClient) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	var resp HelloReply
	if err := c.client.Call(ctx, "ttrpc.Hello", "SayHello", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
